# -*- coding: utf-8 -*-
"""MODULE_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMbPVhAoWwJzzpVEatqECICEQ-CS_WY_
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.ensemble import GradientBoostingRegressor

# Import Bayesian Search from scikit-optimize
from skopt import BayesSearchCV
from skopt.space import Real, Integer

# ==========================================
# 1. SELECT PARAMETER (FULLY DYNAMIC)
# Options: 'iddq_uA' | 'leakage_current_nA' | 'propagation_delay_ns'
# ==========================================
PARAM_PREFIX = 'leakage_current_nA'

col_0h = f'{PARAM_PREFIX}_0h'
col_24h = f'{PARAM_PREFIX}_24h'
col_168h = f'{PARAM_PREFIX}_168h'

df = pd.read_csv('isro_burnin_ess_synthetic_dataset_cleaned.csv')

# Drop NaNs specific to active parameter features & target
clean_df = df.dropna(subset=[col_0h, col_24h, col_168h]).copy()

# Feature engineering
clean_df['drift_0_to_24'] = clean_df[col_24h] - clean_df[col_0h]
clean_df['ratio_24_to_0'] = clean_df[col_24h] / (clean_df[col_0h] + 1e-6)

X = clean_df[[col_0h, col_24h, 'drift_0_to_24', 'ratio_24_to_0']]
y = clean_df[col_168h]

# Log transformation on target (no data leakage)
y_log = np.log1p(y)

X_train, X_test, y_train_log, y_test_log = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

# ==========================================
# 2. BAYESIAN OPTIMIZATION SEARCH SPACE
# ==========================================
search_space = {
    'n_estimators': Integer(50, 300),
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.2, prior='log-uniform'),
    'subsample': Real(0.6, 1.0)
}

opt = BayesSearchCV(
    estimator=GradientBoostingRegressor(random_state=42),
    search_spaces=search_space,
    n_iter=15,  # Number of Bayesian optimization iterations
    cv=3,
    scoring='neg_mean_squared_error',
    random_state=42,
    n_jobs=-1
)

# Fit Bayesian Search
opt.fit(X_train, y_train_log)

# Best estimator found by Bayesian optimization
best_model = opt.best_estimator_

# ==========================================
# 3. EVALUATION & DRIFT PREDICTION
# ==========================================
y_pred_log = best_model.predict(X_test)
y_pred = np.expm1(y_pred_log)
y_test = np.expm1(y_test_log)

r2_log = r2_score(y_test_log, y_pred_log)

# Metric splits
overall_mae = mean_absolute_error(y_test, y_pred)
normal_mask = y_test < 100
normal_mae = mean_absolute_error(y_test[normal_mask], y_pred[normal_mask])

print(f"=== Bayesian Optimization Results ({PARAM_PREFIX}) ===")
print(f"Best Hyperparameters: {opt.best_params_}")
print(f"Log Scale R^2       : {r2_log:.4f}")
print(f"Normal Parts MAE    : {normal_mae:.4f}")
print(f"Overall MAE         : {overall_mae:.4f}")

# ==========================================
# 4. CONSTRUCT & PRINT PREDICTION TABLE (WITH SLOPE & FLAGGING)
# ==========================================
# Construct DataFrame attached to original test index
results_df = X_test.copy()
results_df['Actual_168h'] = y_test
results_df['Predicted_168h'] = y_pred
results_df['Absolute_Error'] = (results_df['Actual_168h'] - results_df['Predicted_168h']).abs()

# Calculate predicted slope (rate of drift from 24h to predicted 168h per hour)
time_delta_hours = 168 - 24
results_df['Predicted_Slope'] = (results_df['Predicted_168h'] - results_df[col_24h]) / time_delta_hours

# Dynamic outlier threshold using IQR (1.5 * IQR above Q3)
q75 = results_df['Predicted_Slope'].quantile(0.75)
q25 = results_df['Predicted_Slope'].quantile(0.25)
iqr = q75 - q25
slope_threshold = q75 + (1.5 * iqr)

# Flag predictions that exceed the dynamic slope threshold
results_df['High_Slope_Flag'] = results_df['Predicted_Slope'] > slope_threshold

# Define table columns to display
table_cols = [col_0h, col_24h, 'Actual_168h', 'Predicted_168h', 'Absolute_Error', 'Predicted_Slope', 'High_Slope_Flag']

print(f"\nDynamic Slope Cutoff Threshold: {slope_threshold:.6f}")
print(f"=== Predictions Table ({PARAM_PREFIX}) ===")
print(results_df[table_cols].head(20).to_string())